### ISSUE TITLE
Handle Non-Zero Return Codes in Process Execution in start_pytorch_task.py

### ISSUE THREAD

**Issue by clemente0420** [FlagOpen/FlagPerf#226]
描述：

在分析位于training/run_benchmarks/pytorch目录下的start_pytorch_task.py文件（第193行）时，可能有必要为正在执行的进程实现返回代码检查。目前，代码使用proc.wait()等待每个进程完成，但缺乏对非零返回代码的适当处理。

建议更改：

修改位于start_pytorch_task.py文件第193行开始的代码块，以为每个进程执行引入返回代码检查。
    1 如果进程的返回代码为非零：
    2 引发一个带有信息性错误消息的异常。
    3 在错误消息中包含进程ID，以识别有问题的进程。

**Comment by clemente0420** [comment]
现有问题是 不管是 模型启动失败还是成功 进程返回值都是0

**Comment by shh2000** [comment]
https://github.com/FlagOpen/FlagPerf/pull/225
