### ISSUE TITLE
环境变量LOCAL_RANK被start_pytorch_task.py改变

### ISSUE THREAD

**Issue by xiaohan4420** [FlagOpen/FlagPerf#274]
描述：
使用training/run_benchmarks/pytorch/start_pytorch_task.py启动训练时，单机单卡场景默认LOCAL_RANK=-1会被https://github.com/FlagOpen/FlagPerf/blob/949141174205e2072fbcc2f13f6de5dc001b0367/training/run_benchmarks/pytorch/start_pytorch_task.py#L177 修改，导致后续错误。
https://github.com/FlagOpen/FlagPerf/blob/949141174205e2072fbcc2f13f6de5dc001b0367/training/run_benchmarks/pytorch/start_pytorch_task.py#L190
比如调用accelerate时会导致https://github.com/huggingface/accelerate/blob/80da9cfb09bb3cc9f1b385cb55d6b90d025a5fd9/src/accelerate/state.py#L195 处分布式类型判断出错。

**Comment by shh2000** [comment]
目前FlagPerf尚不支持采用huggingface accelerate的API进行评测
