### ISSUE TITLE
指标，有几点疑问，请解释下

### ISSUE THREAD

**Issue by baleli668** [FlagOpen/FlagPerf#275]
1. 端到端时间 | e2e_time | 总时间+Perf初始化等时间
这个是指什么？

2. 推理总吞吐量 | p_infer_whole | 实际推理token数除以总推理时间
---实际推理token数，是包含prompt的tokens和complete tokens的总和吗?
     还是只是complete tokens总和？

3.  MMLU回答准确率（few_shots:5）
我看llama2-7b和Aquila_7b_mmlu的 ACC都在50%以下，这样的正确性指标这么低情况下，这样的测试结果有意义吗？

-----------------------------------------------------
指标列表</li></ul>

指标名称 | 指标值索引 | 特殊说明
-- | -- | --
数据精度 | precision | 可选fp32/fp16
批尺寸 | bs |  
硬件存储使用 | mem | 通常称为“显存”,单位为GiB
端到端时间 | e2e_time | 总时间+Perf初始化等时间
验证总吞吐量 | p_val_whole | 实际验证token数除以总验证时间
验证计算吞吐量 | p_val_core | 不包含IO部分耗时
推理总吞吐量 | p_infer_whole | 实际推理token数除以总推理时间
推理计算吞吐量 | *p_infer_core | 不包含IO部分耗时
推理结果 | acc(推理/验证) | MMLU回答准确率（few_shots:5）

</body>
</html>

**Comment by shh2000** [comment]
1. e2etime is short for end_to_end time, =whole training time+perf init time
2. Please refer to the name of this case, which is xxx_MMLU. This case evaluates performance under the MMLU task scenario, and it does not involve the generation of tokens or similar content. Here, it pertains to the number of tokens calculated.
3. Please refer to the meaning of MMLU.

If you have further questions, feel free to reopen this issue or contact via email. Thank you.
