### ISSUE TITLE
在内网环境可以运行么，或者可以设置外网代理之类的么

### ISSUE THREAD

**Issue by hebly723** [FlagOpen/FlagPerf#391]
在内网环境可以运行么，或者可以设置外网代理之类的么

**Comment by shh2000** [comment]
部分运行需要涉及到公网的逻辑，可以预先下载至.cache等目录（例如torchvision的backbone权重）。具体下载到哪个目录需要结合torchvision等仓库的逻辑。随后将data放入同名目录，将其写在datadir的位置，以便一键挂载进容器

**Comment by shh2000** [comment]
如有进一步疑问，请重新开启此issue
