### ISSUE TITLE
deepspeed README的数据集说明

### ISSUE THREAD

**Issue by ZLkanyo009** [FlagOpen/FlagPerf#475]
training/benchmarks/chatglm3_6b/deepspeed/README.md内的 ”https://drive.google.com/drive/folders/1IaD_SIIB-K3Sij_-JjWoPy_UrWqQRdjx 中12GB的openwebtext.tar.xz“，现在在该网站上已经删除，改为urlsf_subsetxxxxxx.tar，建议更新

**Comment by shh2000** [comment]
Thanks for the report @ZLkanyo009.  I can confirm the status. Working on a fix.

**Comment by shh2000** [comment]
Please refer to #495 , i'm working on fix it
