### ISSUE TITLE
stable_diffusion_v1_4推理的数据集没有文档说明，有下载地址吗

### ISSUE THREAD

**Issue by nanlin00** [FlagOpen/FlagPerf#494]
![微信截图_20240325170927](https://github.com/FlagOpen/FlagPerf/assets/70181089/c47ec335-27b2-48da-be91-038a8b55da51)

**Comment by shh2000** [comment]
Thanks for the report @nanlin00. The dataset is vizwiz, val.json. i'll soon push a fix on it. you can use https://vizwiz.org/tasks-and-datasets/image-captioning/ temporarily

**Comment by shh2000** [comment]
Please refer to #495 , i'm working on fix it
