### ISSUE TITLE
openwebtext下载链接失效

### ISSUE THREAD

**Issue by idontkonwher** [FlagOpen/FlagPerf#507]
Hello~， baichuan2-13b[训练说明](https://github.com/FlagOpen/FlagPerf/tree/main/training/benchmarks/baichuan2_13b/deepspeed)中的openwebtext数据集下载[链接](https://drive.google.com/drive/folders/1IaD_SIIB-K3Sij_-JjWoPy_UrWqQRdjx)失效了，麻烦更新下链接或者确认下该数据集与[huggingface](https://huggingface.co/datasets/Skylion007/openwebtext)上的openwebtext数据集是否一致（hf上下载的数据约有20GB+）。

**Comment by shh2000** [comment]
Thanks for the report @idontkonwher ! I can confirm the status, it's likely to be the same reason as #475 (the owner of google drives changed the directory of openwebtext dataset ). 

I'm working on a fix to it. You can try the solution of ChatGLM3 mentioned at #475 temporarily.

**Comment by idontkonwher** [comment]
Thanks for your replay, but I didn't get the key point. Can I just download the urlsf_subsetxxxxxx.tar file directly from Huggingface?  
Or how should I modify the link~ @shh2000

**Comment by shh2000** [comment]
yes. before 2024.3, the origin google drive contained 1 file named xxx.tar.gz, which contained 20 tar file like urlsf_subsetxxx.tar. now, the origin google drive directly provides 20 tar file. you can simply download them, extract all into a directory, and then using our preprocess python file to continue @idontkonwher
