### ISSUE TITLE
mixtral_8x7B 数据集下载地址出错

### ISSUE THREAD

**Issue by cifar10** [FlagOpen/FlagPerf#642]
路径  https://github.com/FlagOpen/FlagPerf/tree/main/training/benchmarks/mixtral_8x7B/megatron ，页面上提供的wudao数据集下载链接出错，具体表现为执行：

（1）wget https://atp-modelzoo-wlcb-pai.oss-cn-wulanchabu.aliyuncs.com/release/models/pai-megatron-patch/llama2-datasets/wudao_llama2bpe_content_document.bin
报错：
![image](https://github.com/FlagOpen/FlagPerf/assets/41565156/986e9a09-900b-407e-8928-588d0c7c1444)

（2）wget https://atp-modelzoo-wlcb-pai.oss-cn-wulanchabu.aliyuncs.com/release/models/pai-megatron-patch/llama2-datasets/wudao_llama2bpe_content_document.idx
报错：
![image](https://github.com/FlagOpen/FlagPerf/assets/41565156/ca572d14-6f8a-4c92-ab3d-7d45f48c9eae)

**Comment by shh2000** [comment]
Hello @cifar10 , I check the origin link in PAI-megatron repo "wget https://atp-modelzoo-wlcb-pai.oss-cn-wulanchabu.aliyuncs.com/release/models/pai-megatron-patch/llama2-datasets/wudao_llamabpe_text_document.idx"

You can use the two links from PAI repo temporarily, we'll fix the link later. Thanks for report!

**Comment by cifar10** [comment]
谢谢，已解决
