### ISSUE TITLE
base directory cannot exec  env.sh ,case env.sh script dir not right, 

### ISSUE THREAD

**Issue by Hodoryu** [FlagOpen/FlagPerf#711]
base -> run.py ->start->start_tasks_in_cluster function, input params "case " `s  value not right.  
    env_dir = os.path.join(
        config.FLAGPERF_PATH, "benchmarks", case, config.VENDOR)
env_dir ：cannot find dir ,

**Comment by shh2000** [comment]
thanks for report, you can see if https://github.com/FlagOpen/FlagPerf/pull/710 can be a solution
